curl -o AspiringZealotPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/AspiringZealotPrimary.jpeg
curl -o AutoPneumaticHammerPrimary.webp https://storage.googleapis.com/secrets-of-toanium-assets/AutoPneumaticHammer.webp
curl -o BlightedCivilianProfile.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/BlightedCivilianProfile.jpeg
curl -o ConfederateSkirmisherPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ConfederateSkirmisherPrimary.jpeg
curl -o CrossbowPrimary.png https://storage.googleapis.com/secrets-of-toanium-assets/CrossbowPrimary.png
curl -o CustomsOfficialPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/CustomsOfficialPrimary.jpeg
curl -o CyberInterface.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/CyberInterface.jpeg
curl -o CyberSuit.webp https://storage.googleapis.com/secrets-of-toanium-assets/Cybersuit.webp
curl -o EarthlingExilePrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/EarthlingExilePrimary.jpg
curl -o EuropanExplorerPrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/EuropanExplorerPrimary.jpg
curl -o GossipGirlPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/GossipGirlPrimary.jpeg
curl -o HiredGunPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/HiredGunPrimary.jpeg
curl -o ItemDeckButterflySwords.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckButterflySwords.jpeg
curl -o ItemDeckCrossbow.png https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckCrossbow.png
curl -o ItemDeckFlamethrower.webp https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckFlamethrower.webp
curl -o ItemDeckFlashbang.webp https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckFlashbang.webp
curl -o ItemDeckFragGrenade.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckFragGrenade.jpeg
curl -o ItemDeckGasGrenade.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckGasGrenade.jpeg
curl -o ItemDeckHandCrossbow.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckHandCrossbow.jpeg
curl -o ItemDeckIncendiaryGrenade.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckIncendiaryGrenade.jpeg
curl -o ItemDeckLegionAR150.webp https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckLegionAR150.webp
curl -o ItemDeckNeedleGrenade.webp https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckNeedleGrenade.webp
curl -o ItemDeckOkaforBeta23.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckOkaforBeta23.jpeg
curl -o ItemDeckOkaforOmega88.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckOkaforOmega88.jpeg
curl -o ItemDeckPlasmaGun.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckPlasmaGun.jpeg
curl -o ItemDeckRevolver.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckRevolver.jpeg
curl -o ItemDeckRocketLauncher.webp https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckRocketLauncher.webp
curl -o ItemDeckScreamer.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemDeckScreamer.jpeg
curl -o ItemK99RapidFireSidearm.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ItemK99RapidFireSidearm.jpeg
curl -o LeatherDuster.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/LeatherDuster.jpeg
curl -o LowlifePrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/LowlifePrimary.jpeg
curl -o LunarDilletantePrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/LunarDilletantePrimary.jpeg
curl -o MagBootsPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/MagBootsPrimary.jpeg
curl -o MarsBackground.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/MarsBackground.jpeg
curl -o MartianGunhandPrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/MartianGunhandPrimary.jpg
curl -o OverclockedDronePrimary.png https://storage.googleapis.com/secrets-of-toanium-assets/OverclockedDronePrimary.png
curl -o OverclockedRepairDronePrimary.png https://storage.googleapis.com/secrets-of-toanium-assets/OverclockedRepairDronePrimary.png
curl -o OverclockedSecurityDronePrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/OverclockedSecurityDronePrimary.jpeg
curl -o PoacherPrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/PoacherPrimary.jpg
curl -o PrivateSecurityPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/PrivateSecurityPrimary.jpeg
curl -o ProfessionalKillerPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ProfessionalKillerPrimary.jpeg
curl -o RepairDronePrimary.png https://storage.googleapis.com/secrets-of-toanium-assets/RepairDronePrimary.png
curl -o RioterPrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/RioterPrimary.jpg
curl -o SecurityDronePrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/SecurityDronePrimary.jpg
curl -o SeekerMechanicPrimary.png https://storage.googleapis.com/secrets-of-toanium-assets/SeekerMechanicPrimary.png
curl -o ShroomPhantasmPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ShroomPhantasmPrimary.jpeg
curl -o SmugglerPrimary.gif https://storage.googleapis.com/secrets-of-toanium-assets/SmugglerPrimary.gif
curl -o StetsonPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/StetsonPrimary.jpeg
curl -o TitanianSaboteurPrimary.jpg https://storage.googleapis.com/secrets-of-toanium-assets/TitanianSaboteurPrimary.jpg
curl -o ZealotPrimary.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/ZealotPrimary.jpeg
curl -o ItemDeckConcussionGrenade.webp https://storage.googleapis.com/secrets-of-toanium-assets/itemDeckConcussionGrenade.webp
