curl -o Circle.png https://storage.googleapis.com/secrets-of-toanium-assets/Circle.png
curl -o Cone.png https://storage.googleapis.com/secrets-of-toanium-assets/Cone.png
curl -o Line.png https://storage.googleapis.com/secrets-of-toanium-assets/Line.png
curl -o Start_1.png https://storage.googleapis.com/secrets-of-toanium-assets/Start_1.png
curl -o Start_2.png https://storage.googleapis.com/secrets-of-toanium-assets/Start_2.png
curl -o Start_3.png https://storage.googleapis.com/secrets-of-toanium-assets/Start_3.png
curl -o Start_4.png https://storage.googleapis.com/secrets-of-toanium-assets/Start_4.png
curl -o alice.png https://storage.googleapis.com/secrets-of-toanium-assets/alice.png
curl -o block-terrain.png https://storage.googleapis.com/secrets-of-toanium-assets/block-terrain.png
curl -o blue-stars-fill.jpg https://storage.googleapis.com/secrets-of-toanium-assets/blue-stars-fill.jpg
curl -o blue-stars-fill.png https://storage.googleapis.com/secrets-of-toanium-assets/blue-stars-fill.png
curl -o bob.png https://storage.googleapis.com/secrets-of-toanium-assets/bob.png
curl -o button_act.png https://storage.googleapis.com/secrets-of-toanium-assets/button_act.png
curl -o button_basic_action.png https://storage.googleapis.com/secrets-of-toanium-assets/button_basic_action.png
curl -o button_basic_attack.png https://storage.googleapis.com/secrets-of-toanium-assets/button_basic_attack.png
curl -o button_done.png https://storage.googleapis.com/secrets-of-toanium-assets/button_done.png
curl -o button_move.png https://storage.googleapis.com/secrets-of-toanium-assets/button_move.png
curl -o button_play.png https://storage.googleapis.com/secrets-of-toanium-assets/button_play.png
curl -o charlie.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/charlie.jpeg
curl -o default-tile.png https://storage.googleapis.com/secrets-of-toanium-assets/default-tile.png
curl -o dif-terrain.png https://storage.googleapis.com/secrets-of-toanium-assets/dif-terrain.png
curl -o door_open.jpg https://storage.googleapis.com/secrets-of-toanium-assets/door_open.jpg
curl -o door_shut.jpg https://storage.googleapis.com/secrets-of-toanium-assets/door_shut.jpg
curl -o dov.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/dov.jpeg
curl -o enter_fullscreen.jpg https://storage.googleapis.com/secrets-of-toanium-assets/enter_fullscreen.jpg
curl -o enter_fullscreen.png https://storage.googleapis.com/secrets-of-toanium-assets/enter_fullscreen.png
curl -o exit_fullscreen.jpg https://storage.googleapis.com/secrets-of-toanium-assets/exit_fullscreen.jpg
curl -o exit_fullscreen.png https://storage.googleapis.com/secrets-of-toanium-assets/exit_fullscreen.png
curl -o explosion.png https://storage.googleapis.com/secrets-of-toanium-assets/explosion.png
curl -o generic-profile-closed.png https://storage.googleapis.com/secrets-of-toanium-assets/generic-profile-closed.png
curl -o generic-profile-picture.png https://storage.googleapis.com/secrets-of-toanium-assets/generic-profile-picture.png
curl -o home_icon.png https://storage.googleapis.com/secrets-of-toanium-assets/home_icon.png
curl -o icons8-delete-48.png https://storage.googleapis.com/secrets-of-toanium-assets/icons8-delete-48.png
curl -o if_fullscreen_118670.png https://storage.googleapis.com/secrets-of-toanium-assets/if_fullscreen_118670.png
curl -o if_fullscreen_exit_118667.png https://storage.googleapis.com/secrets-of-toanium-assets/if_fullscreen_exit_118667.png
curl -o inf_loader.gif https://storage.googleapis.com/secrets-of-toanium-assets/inf_loader.gif
curl -o object_cone.png https://storage.googleapis.com/secrets-of-toanium-assets/object_cone.png
curl -o obs-terrain.png https://storage.googleapis.com/secrets-of-toanium-assets/obs-terrain.png
curl -o play_button.png https://storage.googleapis.com/secrets-of-toanium-assets/play_button.png
curl -o player-widget-gradient.png https://storage.googleapis.com/secrets-of-toanium-assets/player-widget-gradient.png
curl -o scroll.png https://storage.googleapis.com/secrets-of-toanium-assets/scroll.png
curl -o test-wall.jpg https://storage.googleapis.com/secrets-of-toanium-assets/test-wall.jpg
curl -o user-closed.png https://storage.googleapis.com/secrets-of-toanium-assets/user-closed.png
curl -o user.png https://storage.googleapis.com/secrets-of-toanium-assets/user.png
curl -o user1.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/user1.jpeg
curl -o user2.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/user2.jpeg
curl -o user3.png https://storage.googleapis.com/secrets-of-toanium-assets/user3.png