curl -o ComplexBluesTile0.png https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile0.png
curl -o ComplexBluesTile1.png https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile1.png
curl -o ComplexBluesTile2.jpg https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile2.jpg
curl -o ComplexBluesTile3.jpg https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile3.jpg
curl -o ComplexBluesTile4.png https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile4.png
curl -o ComplexBluesTile5.png https://storage.googleapis.com/secrets-of-toanium-assets/ComplexBluesTile5.png
curl -o RaidEntryStairs.jpg https://storage.googleapis.com/secrets-of-toanium-assets/RaidEntryStairs.jpg
curl -o RaidHallway.png https://storage.googleapis.com/secrets-of-toanium-assets/RaidHallway.png
curl -o RaidLargeComplex.jpg https://storage.googleapis.com/secrets-of-toanium-assets/RaidLargeComplex.jpg
curl -o RaidTile0.png https://storage.googleapis.com/secrets-of-toanium-assets/RaidTile0.png
curl -o RaidTile1.jpg https://storage.googleapis.com/secrets-of-toanium-assets/RaidTile1.jpg
curl -o SciFiAirlockEW.jpg https://storage.googleapis.com/secrets-of-toanium-assets/SciFiAirlockEW.jpg
curl -o SciFiAirlockNS.jpg https://storage.googleapis.com/secrets-of-toanium-assets/SciFiAirlockNS.jpg
curl -o SpaceMap1Tile0.png https://storage.googleapis.com/secrets-of-toanium-assets/SpaceMap1Tile0.png
curl -o SpaceMap1Tile1.png https://storage.googleapis.com/secrets-of-toanium-assets/SpaceMap1Tile1.png
curl -o SpaceMap1Tile2.png https://storage.googleapis.com/secrets-of-toanium-assets/SpaceMap1Tile2.png
curl -o SpaceMap1Tile3.png https://storage.googleapis.com/secrets-of-toanium-assets/SpaceMap1Tile3.png
curl -o SpaceMap1Tile4.png https://storage.googleapis.com/secrets-of-toanium-assets/SpaceMap1Tile4.png
curl -o StationBSAngle.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSAngle.jpg
curl -o StationBSBar.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSBar.jpg
curl -o StationBSCells.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSCells.jpg
curl -o StationBSCells1.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSCells1.jpg
curl -o StationBSCellsEntry.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSCellsEntry.jpg
curl -o StationBSCorner.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSCorner.jpg
curl -o StationBSCornerNE.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSCornerNE.jpg
curl -o StationBSGarden.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSGarden.jpg
curl -o StationBSInterior.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSInterior.jpg
curl -o StationBSQuarters.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSQuarters.jpg
curl -o StationBSRedRows.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSRedRows.jpg
curl -o StationBSSide.jpg https://storage.googleapis.com/secrets-of-toanium-assets/StationBSSide.jpg
curl -o TwoWayStreet0.png https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet0.png
curl -o TwoWayStreet1.jpg https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet1.jpg
curl -o TwoWayStreet2.png https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet2.png
curl -o TwoWayStreet3.png https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet3.png
curl -o TwoWayStreet4.jpeg https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet4.jpeg
curl -o TwoWayStreet5.png https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreet5.png
curl -o TwoWayStreetDoorsEW.jpg https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreetDoorsEW.jpg
curl -o TwoWayStreetDoorsNS.jpg https://storage.googleapis.com/secrets-of-toanium-assets/TwoWayStreetDoorsNS.jpg